package lab2;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class caculator extends javax.swing.JFrame {
    private long a=0;
    private     String phepToan="";

    /**
     * Creates new form NewJFrame
     */
    public caculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        hienThi = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        So1 = new javax.swing.JButton();
        So2 = new javax.swing.JButton();
        So3 = new javax.swing.JButton();
        chia = new javax.swing.JButton();
        can2 = new javax.swing.JButton();
        So4 = new javax.swing.JButton();
        So5 = new javax.swing.JButton();
        So6 = new javax.swing.JButton();
        nhan = new javax.swing.JButton();
        phantram = new javax.swing.JButton();
        So7 = new javax.swing.JButton();
        So8 = new javax.swing.JButton();
        So9 = new javax.swing.JButton();
        tru = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        so0 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        cong = new javax.swing.JButton();
        bang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        hienThi.setText("0");
        hienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienThi, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hienThi, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(4, 5));

        So1.setText("1");
        So1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So1ActionPerformed(evt);
            }
        });
        jPanel3.add(So1);

        So2.setText("2");
        So2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So2ActionPerformed(evt);
            }
        });
        jPanel3.add(So2);

        So3.setText("3");
        So3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So3ActionPerformed(evt);
            }
        });
        jPanel3.add(So3);

        chia.setText("/");
        chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiaActionPerformed(evt);
            }
        });
        jPanel3.add(chia);

        can2.setText("sqrt");
        jPanel3.add(can2);

        So4.setText("4");
        So4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So4ActionPerformed(evt);
            }
        });
        jPanel3.add(So4);

        So5.setText("5");
        So5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So5ActionPerformed(evt);
            }
        });
        jPanel3.add(So5);

        So6.setText("6");
        So6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So6ActionPerformed(evt);
            }
        });
        jPanel3.add(So6);

        nhan.setText("*");
        nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanActionPerformed(evt);
            }
        });
        jPanel3.add(nhan);

        phantram.setText("%");
        jPanel3.add(phantram);

        So7.setText("7");
        So7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So7ActionPerformed(evt);
            }
        });
        jPanel3.add(So7);

        So8.setText("8");
        So8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So8ActionPerformed(evt);
            }
        });
        jPanel3.add(So8);

        So9.setText("9");
        So9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So9ActionPerformed(evt);
            }
        });
        jPanel3.add(So9);

        tru.setText("-");
        tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truActionPerformed(evt);
            }
        });
        jPanel3.add(tru);

        jButton15.setText("1/x");
        jPanel3.add(jButton15);

        so0.setText("0");
        so0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so0ActionPerformed(evt);
            }
        });
        jPanel3.add(so0);

        jButton17.setText("+/-");
        jPanel3.add(jButton17);

        xoa.setText("C");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });
        jPanel3.add(xoa);

        cong.setText("+");
        cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congActionPerformed(evt);
            }
        });
        jPanel3.add(cong);

        bang.setText("=");
        bang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangActionPerformed(evt);
            }
        });
        jPanel3.add(bang);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiaActionPerformed
this.a = Long.parseLong(this.hienThi.getText());
if (this.a !=0){
    this.phepToan= "/";
    this.hienThi.setText("0");

}
    }//GEN-LAST:event_chiaActionPerformed

    private void So6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So6ActionPerformed
String gt=this.hienThi.getText();
if (gt.length()<12) {
if (gt.equals("0")) gt="";
long so = Long.parseLong(gt+So6.getText());
this.hienThi.setText(String.valueOf(so));// TODO add your handling code here:
    }          // TODO add your handling code here:
    }//GEN-LAST:event_So6ActionPerformed

    private void so0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_so0ActionPerformed

    private void So1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So1ActionPerformed
String gt=this.hienThi.getText();
if (gt.length()<12) {
if (gt.equals("0")) gt="";
long so = Long.parseLong(gt+So1.getText());
this.hienThi.setText(String.valueOf(so));// TODO add your handling code here:
    }//GEN-LAST:event_So1ActionPerformed
    }
    private void So2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So2ActionPerformed
String gt=this.hienThi.getText();
if (gt.length()<12) {
if (gt.equals("0")) gt="";
long so = Long.parseLong(gt+So2.getText());
this.hienThi.setText(String.valueOf(so));// TODO add your handling code here:
    }          // TODO add your handling code here:
    }//GEN-LAST:event_So2ActionPerformed

    private void So3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So3ActionPerformed
String gt=this.hienThi.getText();
if (gt.length()<12) {
if (gt.equals("0")) gt="";
long so = Long.parseLong(gt+So3.getText());
this.hienThi.setText(String.valueOf(so));// TODO add your handling code here:
    }          // TODO add your handling code here:
    }//GEN-LAST:event_So3ActionPerformed

    private void So4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So4ActionPerformed
String gt=this.hienThi.getText();
if (gt.length()<12) {
if (gt.equals("0")) gt="";
long so = Long.parseLong(gt+So4.getText());
this.hienThi.setText(String.valueOf(so));// TODO add your handling code here:
    }          // TODO add your handling code here:
    }//GEN-LAST:event_So4ActionPerformed

    private void So5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So5ActionPerformed
String gt=this.hienThi.getText();
if (gt.length()<12) {
if (gt.equals("0")) gt="";
long so = Long.parseLong(gt+So5.getText());
this.hienThi.setText(String.valueOf(so));// TODO add your handling code here:
    }          // TODO add your handling code here:
    }//GEN-LAST:event_So5ActionPerformed

    private void So7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So7ActionPerformed
String gt=this.hienThi.getText();
if (gt.length()<12) {
if (gt.equals("0")) gt="";
long so = Long.parseLong(gt+So7.getText());
this.hienThi.setText(String.valueOf(so));// TODO add your handling code here:
    }          // TODO add your handling code here:
    }//GEN-LAST:event_So7ActionPerformed

    private void So8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So8ActionPerformed
String gt=this.hienThi.getText();
if (gt.length()<12) {
if (gt.equals("0")) gt="";
long so = Long.parseLong(gt+So8.getText());
this.hienThi.setText(String.valueOf(so));// TODO add your handling code here:
    }          // TODO add your handling code here:
    }//GEN-LAST:event_So8ActionPerformed

    private void So9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So9ActionPerformed
String gt=this.hienThi.getText();
if (gt.length()<12) {
if (gt.equals("0")) gt="";
long so = Long.parseLong(gt+So9.getText());
this.hienThi.setText(String.valueOf(so));// TODO add your handling code here:
    }          // TODO add your handling code here:
    }//GEN-LAST:event_So9ActionPerformed

    private void hienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienThiActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_hienThiActionPerformed

    private void nhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanActionPerformed
this.a = Long.parseLong(this.hienThi.getText());
if (this.a !=0){
    this.phepToan= "*";
    this.hienThi.setText("0");

}        // TODO add your handling code here:
    }//GEN-LAST:event_nhanActionPerformed

    private void truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truActionPerformed
this.a = Long.parseLong(this.hienThi.getText());
if (this.a !=0){
    this.phepToan= "-";
    this.hienThi.setText("0");

}        // TODO add your handling code here:
    }//GEN-LAST:event_truActionPerformed

    private void congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congActionPerformed
this.a = Long.parseLong(this.hienThi.getText());
if (this.a !=0){
    this.phepToan= "+";
    this.hienThi.setText("0");

}        // TODO add your handling code here:
    }//GEN-LAST:event_congActionPerformed

    private void bangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangActionPerformed

        if(this.phepToan.length()>0){
    long b= Long.parseLong(this.hienThi.getText());
    if(this.phepToan.equals("+")){
        long kq = this.a+b ;
        
        this.hienThi.setText(String.valueOf(kq));
    }else if (this.phepToan.equals("-")){
        long kq = this.a - b;
        this.hienThi.setText(String.valueOf(kq));
    }else if (this.phepToan.equals("*")){
        long kq =this.a * b ;
        this.hienThi.setText(String.valueOf(kq));
    }else if (this.phepToan.equals("/")){
        float kq = (float)this.a / b;
        this.hienThi.setText(String.valueOf(kq));
    
    }
    this.phepToan= "" ; this.a=0;
    
    


        }
// TODO add your handling code here:
    }//GEN-LAST:event_bangActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton So1;
    private javax.swing.JButton So2;
    private javax.swing.JButton So3;
    private javax.swing.JButton So4;
    private javax.swing.JButton So5;
    private javax.swing.JButton So6;
    private javax.swing.JButton So7;
    private javax.swing.JButton So8;
    private javax.swing.JButton So9;
    private javax.swing.JButton bang;
    private javax.swing.JButton can2;
    private javax.swing.JButton chia;
    private javax.swing.JButton cong;
    private javax.swing.JTextField hienThi;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton nhan;
    private javax.swing.JButton phantram;
    private javax.swing.JButton so0;
    private javax.swing.JButton tru;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
